[package]
name = "stats"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
bot_core = { path = "../bot_core" }
rusqlite = { version = "0.40", features = ["bundled"] }
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
teloxide = { version = "0.17" }
log = "0.4.33"
